apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rhods-notebooks
commonLabels:
  app: ope-log-collector

resources:
  - deployment.yaml
  - role.yaml
  - rolebinding.yaml
  - serviceaccount.yaml
