apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - cronjob.yaml
  - rolebinding.yaml
  - serviceaccount.yaml
namespace: ope-rhods-testing-1fef2f